name: Deploy Lambda

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install zip
      run: sudo apt-get install zip -y

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Make deploy script executable
      run: chmod +x deploy.sh

    - name: Run deploy script
      run: ./deploy.sh

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CLIENT_ID_COGNITO: ${{ secrets.CLIENT_ID_COGNITO }}
      PASSWORD: ${{ secrets.PASSWORD_COGNITO }}
      USERNAME_COGNITO: ${{ secrets.USERNAME_COGNITO }}
